Suggested QRV protocol change.
DJ2LS/FreeDATA pull request #236
Opened 2022-07-02 21:28 UTC by kronenpj

Proposed change to QRV frame to facilitate ignoring all QRV frames not addressed to this station.

2022-07-04 08:46 UTC, DJ2LS requested changes

2022-07-04 08:49 UTC, DJ2LS requested changes

2022-07-04 08:49 UTC, DJ2LS commented on tnc/data_handler.py
> +            self.transmit_qrv(static.DXCALLSIGN)
There seems to be also a possible bug in line 2152 `dxcallsign=str(static.DXCALLSIGN, "UTF-8"),` --> this should be also the callsign extracted from CQ frame., same with `dxgrid=str(static.DXGRID, "UTF-8"),`
Could you do me the favor and changing this? Then we possibly avoided another bug

2022-07-04 19:56 UTC, kronenpj commented on tnc/data_handler.py
> +            self.transmit_qrv(static.DXCALLSIGN)
How does this look?

2022-07-04 21:36 UTC, kronenpj commented on test/test_datac0_negative.py
> +    qrv_data = {"type": "test", "command": "send_qrv", "dxcallsign": "DD5GG-3"}
Fair enough. Fixed.

2022-10-04 06:42 UTC, DJ2LS approved these changes

2022-10-05 14:08 UTC, DJ2LS commented
@kronenpj there seems to be a failing ctest. I'm not exactly sure why this happens in this case as I'm not that familiar with them. However, seems to be nearly ready for merging.

2022-10-11 11:13 UTC, DJ2LS commented
We should wait with merging this until session id branch has been merged as this is easier to adjust.

2022-10-11 22:15 UTC, kronenpj commented
Agreed. There's no hurry with this one.

2022-11-08 14:28 UTC, DJ2LS commented
@kronenpj the big work on moving to session IDs in data_handler.py has been done, now. So  we can try working on this again, I think. 
--> Cleanup of PRs and Issues.

2023-01-28 17:58 UTC, DJ2LS commented
this PR needs to be checked. We had some ARQ changes, so better doing this step by step with focus on QRV handling

2023-03-23 09:45 UTC, DJ2LS requested changes
PR outdated

2023-04-22 13:20 UTC, closed without merging